from django.urls import path

from tracker.views import (
    GoalListView,
    GoalCreateView,
    GoalDetailView,
    GoalStageCreateView,
    HabitListView,
    HabitCreateView,
    HabitDetailView,
    CommentaryGoalCreateView,
    CommentaryHabitCreateView,
    GoalDeleteView,
    GoalUpdateView,
    GoalStageUpdateView,
    GoalStageDeleteView,
    HabitDeleteView,
    HabitUpdateView,
    IndexView,
    GoalToggleStatusView,
    GoalToggleAbandonedStatusView,
    GoalToggleStageStatusView,
    GoalToggleStageAbandonedStatusView
)

app_name = "tracker"

urlpatterns = [
    path(
        "",
        IndexView.as_view(),
        name="index"
    ),
    path(
        "goals/",
        GoalListView.as_view(),
        name="goal-list"
    ),
    path(
        "goals/create/",
        GoalCreateView.as_view(),
        name="goal-create"
    ),
    path(
        "goals/<int:pk>/",
        GoalDetailView.as_view(),
        name="goal-detail"
    ),
    path(
        "goals/<int:pk>/delete",
        GoalDeleteView.as_view(),
        name="goal-delete"
    ),
    path(
        "goals/<int:pk>/update",
        GoalUpdateView.as_view(),
        name="goal-update"
    ),
    path(
        "goals/<int:pk>/toggle/",
        GoalToggleStatusView.as_view(),
        name="goal-update-status"
    ),
    path(
        "goals/<int:pk>/toggle/abandoned/",
        GoalToggleAbandonedStatusView.as_view(),
        name="goal-update-status-abandoned"
    ),
    path(
        "goals/<int:goal_id>/create/stage/",
        GoalStageCreateView.as_view(),
        name="goal-create-stage"
    ),
    path(
        "goals/<int:goal_id>/update/stage/<int:pk>/",
        GoalStageUpdateView.as_view(),
        name="goal-update-stage"
    ),
    path(
        "goals/<int:goal_id>/delete/stage/<int:pk>/",
        GoalStageDeleteView.as_view(),
        name="goal-delete-stage"
    ),
    path(
        "goals/<int:goal_id>/toggle/<int:pk>/",
        GoalToggleStageStatusView.as_view(),
        name="goal-update-stage-status"
    ),
    path(
        "goals/<int:goal_id>/toggle/<int:pk>/abandoned/",
        GoalToggleStageAbandonedStatusView.as_view(),
        name="goal-update-stage-status-abandoned"
    ),
    path(
        "goals/<int:pk>/create/commentary/",
        CommentaryGoalCreateView.as_view(),
        name="goal-commentary-create"
    ),
    path(
        "habits/",
        HabitListView.as_view(),
        name="habit-list"
    ),
    path(
        "habits/create/",
        HabitCreateView.as_view(),
        name="habit-create"
    ),
    path(
        "habits/<int:pk>/delete/",
        HabitDeleteView.as_view(),
        name="habit-delete"
    ),
    path(
        "habits/<int:pk>/update/",
        HabitUpdateView.as_view(),
        name="habit-update"
    ),
    path(
        "habits/<int:pk>/",
        HabitDetailView.as_view(),
        name="habit-detail"
    ),
    path(
        "habits/<int:pk>/create/commentary/",
        CommentaryHabitCreateView.as_view(),
        name="habit-commentary-create"
    ),
]
