# Generated by Django 4.1.7 on 2023-04-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_goal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalstage',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=20),
        ),
    ]
