# Generated by Django 4.1.7 on 2023-04-07 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_goalstage_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitDayCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete_date', models.DateField()),
                ('status', models.CharField(choices=[('completed', 'Competed'), ('not_completed', 'Not Competed')], default='not_completed', max_length=13)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_completions', to='tracker.habit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_completions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
