# Generated by Django 4.1.7 on 2023-04-14 15:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0005_alter_goalstage_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Note",
        ),
    ]
