# Generated by Django 4.1.7 on 2023-04-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0006_delete_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="completion_status",
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name="HabitDayCompletion",
        ),
    ]
