# Generated by Django 4.1.7 on 2023-04-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0008_habitlog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="completion_status",
        ),
        migrations.AlterField(
            model_name="habitlog",
            name="completed",
            field=models.BooleanField(),
        ),
    ]
